*&---------------------------------------------------------------------*
*& Module Pool       SAPMZ_TH_MINI_PROJECT1_1
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*
************************************************************************
*  Written By TaeHyeong
*  Reporting Date: '18.12.24
*  Development term: '18.11.19~21
************************************************************************
INCLUDE mz_th_mini_project1_1top                .    " global Data

INCLUDE mz_th_mini_project1_1o01                .  " PBO-Modules
INCLUDE mz_th_mini_project1_1i01                .  " PAI-Modules
INCLUDE mz_th_mini_project1_1f01                .  " FORM-Routines

*GUI Texts
*----------------------------------------------------------
* TH --> TaeHyeong's Mini Project


*Messages
*----------------------------------------------------------
*
* Message class: Hard coded
*   Create Data Complete!!

----------------------------------------------------------------------------------
Extracted by Direct Download Enterprise version 1.3.1 - E.G.Mellodew. 1998-2005 UK. Sap Release 701
