*&---------------------------------------------------------------------*
*& Include Z_TH0701_TYPE_M_PRACTICE_1_TOP                    Module Pool      Z_TH0701_TYPE_M_PRACTICE_1
*&
*&---------------------------------------------------------------------*

PROGRAM  z_th0701_type_m_practice_1.
TABLES zthsoccer.
DATA : click_code TYPE sy-ucomm.
DATA : click_id TYPE i.
DATA : wo_zthsoccer TYPE zthsoccer.