*&---------------------------------------------------------------------*
*& Module Pool       SAPMZ_TH_MINI_PROJECT1_1
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*


INCLUDE MZ_TH_MINI_PROJECT1_1TOP                .    " global Data

 INCLUDE MZ_TH_MINI_PROJECT1_1O01                .  " PBO-Modules
 INCLUDE MZ_TH_MINI_PROJECT1_1I01                .  " PAI-Modules
 INCLUDE MZ_TH_MINI_PROJECT1_1F01                .  " FORM-Routines